// <auto-generated />
using System;
using AdministrationAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministrationAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240901194831_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdministrationAPI.DTO.Fee", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeId"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HourlyImbalanceFee")
                        .HasColumnType("real");

                    b.Property<float?>("ImbalanceFee")
                        .HasColumnType("real");

                    b.Property<float?>("PeakLoadFee")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("datetime2");

                    b.Property<float?>("VolumeFee")
                        .HasColumnType("real");

                    b.Property<float?>("WeeklyFee")
                        .HasColumnType("real");

                    b.HasKey("FeeId");

                    b.ToTable("Fees");
                });
#pragma warning restore 612, 618
        }
    }
}
