services:
  AdministrationAPI:
    image: administrationapi
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Administration;User=sa;Password=4|1cu4nd3
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "4|1cu4nd3"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
